import { NavBar } from '../components/NavBar'
import '../css/globals.css'
import FooterComp from "../components/FooterComp"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <NavBar/>
        {children}

      <FooterComp/>
        </body>
    </html>
  )
}
